"""new field in user model

Revision ID: 589bcf4ea3f8
Revises: 8b79871fc482
Create Date: 2022-09-21 15:17:39.209101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589bcf4ea3f8'
down_revision = '8b79871fc482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
